baseURL = 'https://suejon.github.io/'
languageCode = 'en-us'
# title = 'My New Hugo Site'
theme = "blowfish"

[author]
name = "Jono Sue"
image = "img/author.jpg"
headline = "Full Stack Engineer and Food Eater"
links = [
  { github = "https://github.com/suejon" },
  { linkedin = "https://www.linkedin.com/in/jonosue/" },
  { email = "mailto:jonothansue@gmail.com"}
]

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
    