baseURL = 'https://suejon.github.io/'
languageCode = 'en-us'
title = "Home"
theme = "blowfish"

[author]
name = "Jono Sue"
image = "img/author.jpg"
headline = "Driven by Curiosity | Software Engineer | NZ"
links = [
  { github = "https://github.com/suejon" },
  { linkedin = "https://www.linkedin.com/in/jonosue/" },
  { email = "mailto:jonothansue@gmail.com"}
]

[menu]
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 1
    [[menu.main]]
        name = "Creations"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "Resources"
        url = "/resources/"
        weight = 3
